# Generated by Django 5.1.2 on 2024-11-04 14:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Debt",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("government_id", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("debt_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("debt_due_date", models.DateField()),
                (
                    "debt_id",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("last_processed_row", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="pending", max_length=50)),
                ("processing_duration", models.DurationField(blank=True, null=True)),
                ("user_id", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("file_name", "upload_id")},
            },
        ),
    ]
