# Generated by Django 5.1.2 on 2024-11-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_processingcheckpoint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debt',
            name='invoice_generated',
            field=models.BooleanField(default=False),
        ),
    ]
