# Generated by Django 5.1.2 on 2024-11-04 22:28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_debt_email_sent_debt_invoice_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="upload_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
