# Generated by Django 5.1.2 on 2024-11-04 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_debt_upload_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='upload_id',
        ),
    ]
