repos:
    - repo: local
      hooks:
          - id: black
            name: "format code with black"
            entry: black
            language: system
            types:
                - python
            exclude: ^(.*/migrations/.*|\.pyc$)
          - id: isort
            name: "format imports with isort"
            entry: isort
            language: system
            types:
                - python
            args: ["--profile", "black"]
          - id: flake8
            name: "lint code with flake8"
            entry: flake8
            language: system
            types:
                - python
            exclude: ^(.*/migrations/.*|\.pyc$)
          - id: bandit
            name: "check security"
            entry: bandit
            language: system
            args:
                - --quiet
                - --exclude=tests/
            types:
                - python
default_stages: [pre-commit]